import React from 'react';
import Head from 'next/head';
import Footer from '@components/Footer/Footer';

type Props = {
	withNavbar?: boolean;
	children: React.ReactNode;
};

const GlobalLayout: React.FC<Props> = (props: Props) => (
	<>
		<Head>
			<title>Create Next App</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
		</Head>

		{(props.withNavbar ?? true) && <nav>Navbar</nav>}

		<main>{props.children}</main>

		<Footer />
	</>
);

export default GlobalLayout;
